"use client";

import React from "react";

export function Terms() {
  return (
    <main className="w-full pt-7 md:pt-10 pb-16 px-4 md:px-6 lg:px-8 max-w-5xl mx-auto text-[#0b0f14] dark:text-[#f5f7fa]">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-3 font-inter">Terms and Conditions</h1>
        <p className="italic opacity-70 mb-8 font-inter">Last updated May 22nd, 2025</p>
        <div className="prose max-w-none prose-slate dark:prose-invert prose-headings:font-inter prose-p:font-inter prose-a:text-[#19ad7d]">
          <p className="mb-4">These Terms and Conditions (“Terms”) sets forth the terms and conditions that apply to access and use of the Services (as defined below) of Enzy Technologies, LLC (“Provider”) by the customer set forth on an Order Form submitted to Provider (“Customer”). These Terms, together with (i) any order form submitted by Customer and accepted by Provider (“Order Form”), any statement of work submitted to and accepted by Provider (“SOW”), and (iii) Provider&rsquo;s Privacy Policy found at <a href="/privacy-policy">https://enzy.ai/privacy-policy</a>, constitute the “Agreement.” Provider and Customer may be referred to herein individually as a “Party” or collectively as the “Parties.”</p>
          <p className="mb-4">This Agreement becomes binding and effective on Customer upon the earliest of: (1) when you access or use the Services, including accessing the Services after changes to this Agreement in accordance to Section 11.6 below, (2) when you click an “I Accept,” “Sign up” or similar button or check box referencing this Agreement, or (3) when you enter into an Order Form (“Effective Date”).</p>
          <p className="mb-4">BEFORE ACCEPTING THIS AGREEMENT, CUSTOMER IS ADVISED TO CAREFULLY READ THE TERMS OF THIS AGREEMENT AND ANY APPLICABLE DOCUMENTATION. BY CLICKING TO ACCEPT THIS AGREEMENT, CUSTOMER (1) AGREES TO BE BOUND BY AND BECOMES A PARTY TO THIS AGREEMENT AND (2) CONFIRMS THAT THE INDIVIDUAL ENTERING THIS AGREEMENT HAS AUTHORITY TO SO BIND CUSTOMER WITHOUT FURTHER ACTION BY CUSTOMER. IF CUSTOMER DOES NOT AGREE TO THE TERMS OF THIS AGREEMENT, CUSTOMER SHOULD NOT CLICK THE “AGREE” BUTTON AND THE SERVICES WILL NOT BE USABLE.</p>
          <p className="mb-4">WHEREAS, Customer desires to utilize Provider&rsquo;s Services as described herein and Provider desires to provide Customer access to such Services, subject to the terms and conditions set forth in the Agreement;</p>
          <p className="mb-4">NOW, THEREFORE, in consideration of the mutual covenants, terms and conditions set forth herein and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the Parties agree as follows:</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">1. Definitions</h2>
          <p className="mb-4"><strong>1.1. “Access Credentials”</strong> means any username, identification number, password, license or security key, security token, PIN, or other security code, method, technology, or device used, alone or in combination, to verify an individual&rsquo;s identity and authorization to access and use the Services.</p>
          <p className="mb-4"><strong>1.2. “Authorized Users”</strong> means Customer&rsquo;s employees, consultants, contractors, and agents (a) who are authorized by Customer to access and use the Services in accordance with the Agreement, (b) for whom access to the Services has been purchased hereunder, and (c) who have accepted and are bound by the EULA.</p>
          <p className="mb-4"><strong>1.3. “Customer Data”</strong> means information, data, and other content, in any form or medium, that is collected, uploaded, or otherwise processed, directly or indirectly by Customer through the Services. Customer Data may, in some situations, include Authorized Users&rsquo; Personal Information or Sensitive Personal Information. Customer Data does not include Resultant Data or Usage Data.</p>
          <p className="mb-4"><strong>1.4. “Data Protection Laws”</strong> mean collectively any applicable data protection, privacy, or similar laws applicable to the processing of Personal Information in the jurisdiction where Services are performed or used or applicable to the Personal Information processed as part of the Services, if any.</p>
          <p className="mb-4"><strong>1.5. “EULA”</strong> means Provider&rsquo;s end user license agreement to which each Authorized User must agree before accessing the Services.</p>
          <p className="mb-4"><strong>1.6. “Intellectual Property Rights”</strong> means all registered and unregistered rights granted, applied for, or otherwise now or hereafter in existence under or related to any patent, copyright, trademark, trade secret, data or database protection, or other intellectual property rights Laws and all similar or equivalent rights or forms of protection, in any part of the world.</p>
          <p className="mb-4"><strong>1.7. “Law”</strong> means any statute, law, ordinance, regulation, rule, code, order, constitution, treaty, common law, judgment, decree, or other requirement of any federal, state, local, or foreign government or political subdivision thereof, or any arbitrator, court, or tribunal of competent jurisdiction. “Law” includes all Data Protection Laws.</p>
          <p className="mb-4"><strong>1.8. “Personal Information”</strong> means any information relating to an identified or identifiable individual and is protected similarly as personal data or personally identifiable information under Data Protection Laws. Personal Information may include Sensitive Personal Information.</p>
          <p className="mb-4"><strong>1.9. “Resultant Data”</strong> means data or information related to or derived from Customer Data or an Authorized User&rsquo;s Personal Information that is processed by Provider in an aggregate, de-identified, or anonymized manner, including to compile statistical and performance information related to the provision and operation of the Services.</p>
          <p className="mb-4"><strong>1.10. “Sensitive Personal Information”</strong> means a class of Personal Information including (a) social security number, passport number, driver&rsquo;s license number, or similar identifier, (b) credit or debit card number (other than truncated digits), financial information, banking account numbers or passwords, (c) employment, financial, genetic, biometric or health information, (d) racial, ethnic, political or religious affiliation, trade union membership, or information about sexual life or sexual orientation, (e) account passwords, (f) criminal history, or (g) any other information or combinations of information that falls within the definition of “special categories of data” under any other Data Protection Law.</p>
          <p className="mb-4"><strong>1.11. “Services”</strong> means Provider&rsquo;s services identified on the Order Form and each SOW (as applicable) that enables Customer&rsquo;s and Authorized Users&rsquo; access to such services. “Services” specifically includes access to and use of Provider&rsquo;s Enzy mobile and web application.</p>
          <p className="mb-4"><strong>1.12. “Usage Data”</strong> means any data or other information processed by or on behalf of Provider relating to the provision, access, use, operation, or performance of the Services by or on behalf of Customer and its Authorized Users, including any data or other information derived therefrom.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">2. Services</h2>
          <p className="mb-4"><strong>2.1. License and Use of Services.</strong> Subject to and conditioned on Customer&rsquo;s compliance with the terms of the Agreement and the Authorized Users&rsquo; compliance with the EULA, Provider grants to Customer a non-exclusive, limited, revocable, non-transferable, and non-sublicensable right to access and use the Services during the Term, solely for use by Customer and its Authorized Users, where applicable, in accordance with the Agreement. Such use is limited to Customer&rsquo;s internal use. Provider will provide to Customer the Access Credentials for Customer&rsquo;s administrators within a reasonable time following the Effective Date. Customer, through its administrators, can then create Access Credentials for the Authorized Users. Access Credentials are personal to Customer and each Authorized User and may not be shared with or used by any other party. Customer has and will retain sole responsibility for all access to and use of the Services by any Customer personnel and Authorized User and will securely administer the distribution and use of all Access Credentials to protect against any unauthorized access to or use of the Services. Customer shall not permit Authorized Users in excess of the number allotted on the Order Form unless approved in writing by Provider.</p>
          <p className="mb-4"><strong>2.2. Use Restrictions.</strong> Customer shall not (and shall not allow any Authorized User or third party to): (a) copy, modify, adapt, translate or otherwise create derivative works or improvements of the Services, (b) reverse engineer, decompile, disassemble, decode, adapt or otherwise attempt to discover the source code of the Services, in whole or in part, (c) rent, lease, lend, sell, sublicense, assign, distribute, publish or otherwise transfer or make available rights in or to the Services, (d) remove, delete, alter, or obscure any specifications, documentation, warranties, or disclaimers, or any copyright, trademark, patent, or other intellectual property or proprietary rights notices from any Services, including any copy thereof, (e) use, post, transmit or introduce any device, software or routine which interferes or attempts to interfere with the operation of the Services, or (f) access or use the Services in any manner or for any purpose: (i) that infringes, misappropriates, or otherwise violates any Intellectual Property Right or other right of any third party (including by any unauthorized access to, misappropriation, use, alteration, destruction, or disclosure of the data of any other Provider customer); (ii) to gather competitive information or compete directly or indirectly with Provider; or (iii) that violates any applicable Law. Customer agrees to comply with all applicable Laws and regulations in Customer&rsquo;s use of and access to the Services.</p>
          <p className="mb-4"><strong>2.3. Community Guidelines.</strong> The Services may permit Customer and Authorized Users to upload data, information, or other materials, including Customer Data, in a manner that makes such data, information, or other materials publicly available and/or accessible to other users of the Services. Customer is solely responsible for any data, information, or other materials, including Customer Data that it uploads to the Services. Neither Customer nor any Authorized User will use the Services to do any of the following:</p>
          <ul className="mb-4 list-disc pl-6 space-y-1">
            <li>(a) Harass, threaten, disrupt, or defraud other users or otherwise create or contribute to an unsafe, harassing, threatening or disruptive environment;</li>
            <li>(b) Make unsolicited offers, advertisements, political campaigns, proposals, or send junk mail or “spam” to other users;</li>
            <li>(c) Impersonate another person or access another user&rsquo;s account;</li>
            <li>(d) Share Provider-issued passwords with any third party or encourage any other users to do so;</li>
            <li>(e) Upload any material that is damaging to computer systems or data of Provider or users of the Services (e.g. viruses, corrupted files, or any other similar software files); and</li>
            <li>(f) Upload or post any material that is inappropriately violent, unduly graphic, pornographic, bigoted, derogatory, racist, or offensive, or that violates the Intellectual Property Rights of any third party.</li>
          </ul>
          <p className="mb-4">Customer acknowledges that Provider has the right, but no obligation, to monitor any data, information, or other materials that Customer or Authorized Users may upload to the Services. Provider may remove any data, information, or other material that Provider determines, in its sole discretion, violates the foregoing requirements; provided, that Provider takes no responsibility and assumes no liability for any data, information, or other material that is uploaded to the Services by Customer or any Authorized User.</p>
          <p className="mb-4"><strong>2.4. Changes.</strong> Provider reserves the right, in its sole discretion, to make any changes to the Services that it deems necessary or useful to: (a) maintain or enhance: (i) the quality or delivery of the Services to its customers; (ii) the competitive strength of or market for the Services; or (iii) the Services&rsquo; cost efficiency or performance; or (b) to comply with applicable Law.</p>
          <p className="mb-4"><strong>2.5. Suspension or Termination of Services.</strong> Provider may, directly or indirectly, suspend, terminate, or otherwise deny Customer&rsquo;s, Authorized Users&rsquo;, or any other person&rsquo;s access to or use of all or any part of the Services, without incurring any resulting obligation or liability, if Provider believes that there has been a material breach of Customer&rsquo;s obligations under the Agreement, a security breach, a violation of Law, an Authorized User&rsquo;s breach of the EULA, or an Authorized User&rsquo;s request to opt-out of the Services or exercise of any right under Data Protection Laws. This Section 2.5 does not limit any of Provider&rsquo;s other rights or remedies, whether at Law, in equity, or under the Agreement.</p>
          <p className="mb-4"><strong>2.6. Electronic Messaging.</strong> Provider may include the ability to communicate with Authorized Users using SMS, other text message mechanisms, email, or other electronic messaging platforms (each an “Electronic Message”). To the extent Customer&rsquo;s Authorized Users opt-in to Electronic Messages, Customer shall ensure that all Electronic Messages comply with applicable Law.</p>
          <p className="mb-4"><strong>2.7. Promotions.</strong> Customer may have the ability to run promotions within the Services for its Authorized Users. Customer is solely responsible for payment or delivery of any promotional prize or giveaway it runs or offers through the Services.</p>
          <p className="mb-4"><strong>2.8. Technical Support Services; Availability.</strong> Provider shall host, serve, distribute, and enable the availability of the Services and ensure that the same are available to Customer, its affiliates, and Authorized Users in accordance with the specifications and service level criteria and performance metrics set forth on Exhibit A (“Service Levels”).</p>
          <p className="mb-4"><strong>2.9. Onboarding Tool.</strong> This section applies if Customer signs up for Enzy&rsquo;s onboarding tool (“Onboarding Tool”).</p>
          <ul className="mb-4 list-none pl-6 space-y-2">
            <li>(a) The Onboarding Tool will allow Customer to gather documents and information to efficiently onboard new employees and contractors (“New Person”), including but not limited to, W-9 forms, identity verification, and forms of identification, banking information, and background checks (“Onboarding Information”). Customer may allow access to the Onboarding Tool to any New Person for use in gathering the Onboarding Information.</li>
            <li>(b) Enzy does not have any responsibility to verify the accuracy of any Onboarding Information. Customer is solely responsible to review and ensure that all Onboarding Information is complete and accurate.</li>
            <li>(c) Customer acknowledges that the Onboarding Information will likely contain Sensitive Personal Information. Customer shall ensure that each New Person consents to Enzy&rsquo;s processing of Sensitive Personal Information.</li>
            <li>(d) Customer shall satisfy all federal, state, and local legal obligations, including withholding liabilities, payroll returns to tax agencies, submitting appropriate tax filings, and any other related obligation. Customer acknowledges that the Onboarding Tool does not fulfill any reporting requirements, payroll functions, or other human-resource related functions. Customer shall indemnify Enzy for any third-party claim, including from any New Person, related to Customer&rsquo;s obligation to satisfy any withholding and reporting requirements.</li>
          </ul>
          <p className="mb-4"><strong>2.10. Professional Services.</strong> Provider will provide any professional services, including without limitation, customization, implementation, or other services (“Professional Services”) that are described in an applicable SOW that may be executed between the Parties from time to time. Provider will diligently perform the Professional Services in accordance with the applicable SOW, including any specifications in the SOW. Provider will use commercially reasonable efforts to complete the Professional Services.</p>
          <ul className="mb-4 list-none pl-6 space-y-2">
            <li>(e) <strong>Non-Exclusivity of Professional Services.</strong> Customer acknowledges that Provider may provide services similar to the Professional Services on behalf of other Provider customers. Provider may work for other customers without restriction, even if work is done for a potentially competing company or individual. Nothing in the Agreement may be construed to limit Providers&rsquo; business, including the provision of the Services to other Provider customers.</li>
            <li>(f) <strong>Ownership.</strong> Notwithstanding anything to the contrary in the Agreement or any SOW, Provider retains ownership of all of Provider&rsquo;s Intellectual Property Rights directly or indirectly related to the Services, including all Professional Services performed under any SOW, whether now existing or whether conceived, developed, or reduced to practice, solely or jointly with Customer, in connection with the Professional Services or otherwise related to Provider&rsquo;s Services under this Agreement.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-10 mb-4">3. Fees and Payment</h2>
          <p className="mb-4">Customer shall pay Provider the fees set forth in the Order Form or any applicable SOW, including any costs of the Services that Provider passes through to Customer (“Fees”). Specifically, if Customer uses the text messaging feature in the Services, Provider may pass through the costs associated with sending each text message (currently $0.007 per message). Unless otherwise set forth in the Order Form or applicable SOW: (a) for each Renewal Term (as defined below), Provider, in its sole discretion, may increase Fees up to seven percent (7%), and (b) invoices are due and payable in United States dollars within thirty (30) days after the invoice date, without deduction or setoff. Customer shall pay or reimburse Provider for all federal, state, local, sales, use, value added, excise, or other taxes, fees, or duties arising out of or related to the Agreement or the transactions contemplated hereby, other than net income taxes imposed on Provider. Any amount not paid when due is subject to finance charges equal to 1.5% of the unpaid balance per month or the highest rate permitted by applicable usury law, whichever is more, determined and compounded daily from the date due until the date paid.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">4. Confidentiality</h2>
          <p className="mb-4"><strong>4.1. Confidential Information.</strong> In connection with this Agreement each Party (as the “Disclosing Party”) may disclose or make available Confidential Information to the other Party (as the “Receiving Party”). Subject to Section 4.2, “Confidential Information” means information in any form or medium (whether oral, written, electronic, or other) that the Disclosing Party considers confidential or proprietary, or information that should by its nature be considered confidential, including information consisting of or relating to the Disclosing Party&rsquo;s technology, trade secrets, know-how, business operations, plans, strategies, customers, and pricing, and information with respect to which the Disclosing Party has contractual or other confidentiality obligations, in each case whether or not marked, designated, or otherwise identified as “confidential”. Without limiting the foregoing, the Services and the underlying data (including Resultant Data and Usage Data) are the Confidential Information of Provider and Customer Data is the Confidential Information of Customer.</p>
          <p className="mb-4"><strong>4.2. Exclusions.</strong> Confidential Information does not include information that: (a) was rightfully known to the Receiving Party without restriction on use or disclosure prior to such information&rsquo;s being disclosed or made available to the Receiving Party in connection with the Agreement; (b) was or becomes generally known by the public other than by the Receiving Party&rsquo;s or any of its Representatives&rsquo; noncompliance with this Agreement; (c) was or is received by the Receiving Party on a non-confidential basis from a third party that was not known to the Receiving Party to be under any obligation to maintain its confidentiality; or (d) was or is independently developed by the Receiving Party without reference to or use of any Confidential Information.</p>
          <p className="mb-4"><strong>4.3. Protection of Confidential Information.</strong> Neither Party shall use the Confidential Information of the other Party for any purpose except to exercise its rights and perform its obligations under this Agreement. Neither Party shall disclose, or permit to be disclosed, either directly or indirectly, any Confidential Information except to its representatives who: (i) need to know such Confidential Information for purposes of the Receiving Party&rsquo;s exercise of its rights or performance of its obligations under and in accordance with the Agreement; (ii) have been informed of the confidential nature of the Confidential Information and the Receiving Party&rsquo;s obligations under this Section 4.3; and (iii) are bound by confidentiality and restricted use obligations at least as protective of the Confidential Information as the terms set forth in this Section 4. Each Party shall safeguard the other Party&rsquo;s Confidential Information from unauthorized use, access, or disclosure using at least the degree of care it uses to protect its similarly sensitive information and in no event less than a reasonable degree of care, shall promptly notify the Disclosing Party of any unauthorized use or disclosure of Confidential Information, and cooperate with the Disclosing Party to prevent further unauthorized use or disclosure.</p>
          <p className="mb-4"><strong>4.4. Compelled Disclosures.</strong> If the Receiving Party or any of its representatives is compelled by applicable Law to disclose any Confidential Information then, to the extent permitted by applicable Law, the Receiving Party shall: (a) promptly, and prior to such disclosure, notify the Disclosing Party in writing of such requirement so that the Disclosing Party can seek a protective order or other remedy or waive its rights under Section 4.3; and (b) provide reasonable assistance to the Disclosing Party, at the Disclosing Party&rsquo;s sole cost and expense, in opposing such disclosure or seeking a protective order or other limitations on disclosure. If the Disclosing Party waives compliance or, after providing the notice and assistance required under this Section 4.4, the Receiving Party remains required by Law to disclose any Confidential Information, the Receiving Party shall disclose only that portion of the Confidential Information that the Receiving Party is legally required to disclose.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">5. Non-Solicitation</h2>
          <p className="mb-4">During the Term and for one (1) year thereafter, neither Party may, and shall not assist any other person to, directly or indirectly recruit, employ, engage as an independent contractor, or solicit for employment or engagement as an independent contractor any person that is, or within the six (6) months prior to such recruitment, hiring, engagement or solicitation, was, employed or engaged as an independent contractor by the other Party; provided, that the foregoing obligation does not apply to a bona fide response to a general job posting or solicitation that was not targeted at a particular employee or contractor.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">6. Intellectual Property Rights</h2>
          <p className="mb-4"><strong>6.1. Services.</strong> As between Customer and Provider, Provider is and will remain the sole and exclusive owner of all right, title, and interest in and to the Services and any underlying data (excluding Customer Data, but including Resultant Data and Usage Data), including all Intellectual Property Rights therein, and with respect to third-party materials, the applicable third-party providers own all right, title and interest, including all Intellectual Property Rights, in and to such third-party materials. Customer has no right, license, or authorization with respect to any of the Services or underlying data (other than the Customer Data) except as expressly set forth in Section 2 or the applicable third-party license, in each case subject to any restrictions in the Agreement (or such third-party license, as applicable). All other rights in and to the Services are expressly reserved by Provider. To the extent Customer has any right, title or interest in the Resultant Data or Usage Data, Customer hereby assigns all such right, title, and interest in and to such Resultant Data and Usage Data, including in each case, all Intellectual Property Rights relating thereto. Customer hereby grants to Provider a royalty-free, fully paid-up, nonexclusive, perpetual, irrevocable, worldwide, transferable (only to a successor in interest by way of merger, reorganization or sale of all or substantially all assets of the business unit performing the Services or equity, or operation of law), sublicensable license to use, copy, modify, or distribute, including by incorporating into the Services, any suggestions, enhancement requests, recommendations or other feedback provided by Customer, its users, and any Authorized User, relating to the operation of the Services. Included in such license is the right to (i) identify or reference Customer as a user of Provider&rsquo;s Services and a right to use Customer&rsquo;s logo in connection therewith, and (ii) perform and make public a case study with respect to Customer and its use of the Services and results of the Services.</p>
          <p className="mb-4"><strong>6.2. Customer Data.</strong> As between Customer and Provider, Customer is and will remain the sole and exclusive owner of all right, title, and interest in and to all Customer Data, including all Intellectual Property Rights embodied therein, subject to the rights and permissions granted in this Section 6.2. Customer hereby grants to Provider a worldwide, non-exclusive, perpetual, irrevocable, royalty-free, fully paid-up, sublicensable and transferable license to (i) use, copy, process, transmit, store, host, edit, modify, aggregate, combine, reproduce, distribute, display, perform, and prepare derivative works of the Customer Data in connection with the Services and (ii) otherwise access, use or make reference to any Intellectual Property Rights in the Customer Data: (a) to provide the Services including to enable the Customer and any Authorized Users to access and use the Services; (b) for diagnostic purposes; (c) to make any changes or improvements to the Services, including as set forth in Section 2, whether requested by the Customer or not; (d) to develop other Services; and (e) as reasonably required for the performance of Provider&rsquo;s obligations under the Agreement. For clarity, the foregoing license continues after termination of the Agreement with respect to any Customer Data that Customer or any Authorized User posts or otherwise makes publicly available through the Services. To the extent any Customer Data constitutes Personal Information, the terms of Provider&rsquo;s Privacy Policy apply.</p>
          <p className="mb-4"><strong>6.3. Personal Information.</strong> Each Party shall use and process any Personal Information that such Party has access to in connection with the Agreement in accordance with applicable Data Protection Laws.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">7. Representations, Warranties and Covenants</h2>
          <p className="mb-4"><strong>7.1. Mutual Representations and Warranties.</strong> Each Party represents and warrants to the other Party that (a) it is duly organized, validly existing, and in good standing under the Laws of the jurisdiction of its incorporation or other organization, (b) it has the full right, power, and authority to enter into and perform its obligations and grant the rights, licenses, consents, and authorizations it grants or is required to grant under the Agreement; and (c) when executed/electronically accepted and delivered by both Parties, the Agreement will constitute the legal, valid, and binding obligation of such Party, enforceable against such Party in accordance with its terms.</p>
          <p className="mb-4"><strong>7.2. Additional Customer Representations, Warranties, and Covenants.</strong> Customer represents, warrants, and covenants to Provider that Customer owns or otherwise has and will have the necessary rights and consents in and relating to the Customer Data so that, as received by Provider and processed in accordance with the Agreement, they do not and will not infringe, misappropriate, or otherwise violate any Intellectual Property Rights, or any privacy or other rights of any third party or violate any applicable Law. To the extent Customer has access to and utilizes any Authorized Users&rsquo; Personal Information in the Services, Customer represents and warrants that Customer has secured all permissions necessary to allow Provider to process such Personal Information.</p>
          <p className="mb-4"><strong>7.3. Third Party Software.</strong> The Services may contain or require use of third-party software that require notices or additional terms and conditions. Provider will deliver such required third-party notices or additional terms and conditions to Customer from time to time upon written request and are incorporated by reference into the Agreement. By accepting the Agreement, Customer is also accepting the additional terms and conditions, if any, set forth in such third-party notices or terms and conditions. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THE AGREEMENT, PROVIDER MAKES NO WARRANTIES AND ACCEPTS NO LIABILITY WITH RESPECT TO THIRD-PARTY SOFTWARE.</p>
          <p className="mb-4"><strong>7.4. DISCLAIMER OF WARRANTIES.</strong> EXCEPT FOR THE EXPRESS WARRANTIES AND COVENANTS SET FORTH IN SECTION 7.1, ALL SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE.” PROVIDER DOES NOT WARRANT THAT CUSTOMER&rsquo;S USE OR INTEGRATION OF THE SERVICES WITH CUSTOMER&rsquo;S PLATFORM WILL SATISFY CUSTOMER&rsquo;S REQUIREMENTS OR SPECIFICATIONS. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, PROVIDER HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">8. Indemnification</h2>
          <p className="mb-4"><strong>8.1. Provider Indemnification.</strong> Provider shall indemnify, defend, and hold harmless Customer from and against any and all losses, damages, deficiencies, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, or expenses of whatever kind, including reasonable attorney fees (“Losses”) incurred by Customer resulting from any claim or action by a third party that Customer&rsquo;s use of the Services (excluding third party materials) in accordance with the Agreement infringes or misappropriates such third party&rsquo;s Intellectual Property Rights. The foregoing obligation does not apply to the extent that the alleged infringement arises from (a) modification of the Services other than: (i) by or on behalf of Provider; or (ii) with Provider&rsquo;s written approval in accordance with Provider&rsquo;s written specification, (b) combination of the Services (or any portion thereof) with any other product or service, (c) failure to timely implement any modifications, upgrades, replacements or enhancements made available to Customer by or on behalf of Provider, (d) Customer Data, (e) Authorized User Personal Information (unless required by Data Protection Laws), (f) Provider implementing instructions or requests of Customer, or (g) any act, omission, or other matter described in Section 8.2, whether or not the same results in any claim or action against or Losses by any Provider Indemnitee.</p>
          <p className="mb-4"><strong>8.2. Customer Indemnification.</strong> Customer shall indemnify, defend, and hold harmless Provider and its affiliates and each of its and their respective officers, directors, employees, agents, successors and assigns (each, a “Provider Indemnitee”) from and against any and all Losses incurred by such Provider Indemnitee resulting from any claim or action by a third party (other than an affiliate of a Provider Indemnitee) to the extent that such Losses arise out of or result from, or are alleged to arise out of or result from (a) Customer&rsquo;s use of the Services, (b) Customer Data, including any processing of Customer Data by or on behalf of Provider in accordance with the Agreement, (c) any other materials or information (including any documents, data, specifications, content, or technology) provided by or on behalf of Customer or any Authorized User, (d) allegation of facts that, if true, would constitute Customer&rsquo;s breach of any of its representations, warranties, covenants, or obligations under the Agreement, or (e) negligence or more culpable act or omission (including recklessness or willful misconduct) by Customer or any third party on behalf of Customer, in connection with the Agreement. Customer shall also indemnify, defend, and hold harmless any Provider Indemnitee from any claim or Losses arising out of or related to Customer&rsquo;s offer of a promotion as described in Section 2. The foregoing obligation does not apply to the extent that the alleged Losses arise from any act or other matter described in Section 8.1 to the extent Provider is indemnifying Customer for such act or other matter.</p>
          <p className="mb-4"><strong>8.3. Indemnification Procedure.</strong> Each Party shall promptly notify the other Party in writing of any claim or action for which such Party believes it is entitled to be indemnified. The Party seeking indemnification shall cooperate with the other Party at the indemnitor&rsquo;s sole cost and expense. The indemnitor shall promptly assume control of the defense and shall employ counsel of its choice to handle and defend the same, at the indemnitor&rsquo;s sole cost and expense. The Party seeking indemnification may participate in and observe the proceedings at its own cost and expense with counsel of its own choosing. The indemnitor shall not settle any claim or action in any manner that adversely affects the rights of the Party seeking indemnification without that Party&rsquo;s prior written consent, which shall not be unreasonably withheld or delayed. If the indemnitor fails or refuses to assume control of the defense of such claim or action, the Party seeking indemnification shall have the right, but no obligation, to defend against such claim or action, including settling such claim or action after giving notice to the indemnitor, in each case in such manner and on such terms as the Party seeking indemnification may deem appropriate. The Party seeking indemnification&rsquo;s failure to perform any obligations under this Section 8.3 will not relieve the indemnitor of its obligations under this Section 8, except to the extent that the indemnitor can demonstrate that it has been prejudiced as a result of such failure.</p>
          <p className="mb-4"><strong>8.4. Mitigation.</strong> If any of the Services are, or in Provider&rsquo;s opinion are likely to be, claimed to infringe, misappropriate, or otherwise violate any third-party Intellectual Property Right, or if Customer&rsquo;s or any Authorized User&rsquo;s use of the Services is enjoined or threatened to be enjoined, Provider may, at its option and sole cost and expense (a) obtain the right for Customer to continue to use the Services materially as contemplated by the Agreement, (b) modify or replace the Services, in whole or in part, to seek to make the Services (as so modified or replaced) non-infringing, while providing materially equivalent features and functionality, in which case such modifications or replacements will constitute Services, as applicable, under the Agreement, or (c) by written notice to Customer, terminate this Agreement with respect to all or part of the Services and require Customer to immediately cease any use of the Services or any specified part or feature thereof, provided that if such termination occurs prior to the first anniversary of the Effective Date, subject to Customer&rsquo;s compliance with its post-termination obligations set forth in Section 10.3, Customer will be entitled to a pro rata refund.</p>
          <p className="mb-4"><strong>8.5. Sole Remedy.</strong> THIS SECTION 8 SETS FORTH CUSTOMER&rsquo;S SOLE REMEDIES AND PROVIDER&rsquo;S SOLE LIABILITY AND OBLIGATION FOR ANY ACTUAL, THREATENED, OR ALLEGED CLAIMS THAT THE SERVICES OR ANY SUBJECT MATTER OF THIS AGREEMENT INFRINGES, MISAPPROPRIATES, OR OTHERWISE VIOLATES ANY INTELLECTUAL PROPERTY RIGHTS OF ANY THIRD PARTY.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">9. Limitations of Liability</h2>
          <p className="mb-4">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, PROVIDER WILL NOT BE LIABLE FOR CUSTOMER&rsquo;S LOST REVENUES OR INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, EVEN IF PROVIDER OR ITS AFFILIATES HAVE BEEN ADVISED OF, KNEW OR SHOULD HAVE KNOWN THAT SUCH DAMAGES WERE POSSIBLE AND EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY. PROVIDER&rsquo;S (AND ITS AFFILIATES&rsquo;) TOTAL CUMULATIVE LIABILITY TO CUSTOMER OR ANY OTHER PARTY FOR ANY LOSS OR DAMAGES RESULTING FROM CLAIMS OR ACTIONS ARISING OUT OF OR RELATING TO THIS AGREEMENT WILL NOT EXCEED THE TOTAL AMOUNTS PAID TO PROVIDER BY CUSTOMER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTH PERIOD PRECEDING THE EVENT GIVING RISE TO THE CLAIM. THE FOREGOING LIMITATIONS APPLY EVEN IF ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">10. Term and Termination</h2>
          <p className="mb-4"><strong>10.1. Term.</strong> The Agreement commences as of the Effective Date and will continue in effect as detailed on an Order Form, unless earlier terminated by a Party in accordance with the terms of this Agreement (“Initial Term”). Following the Initial Term, this Agreement automatically renews for successive twelve (12) month terms (each, a “Renewal Term” and together with the Initial Term, the “Term”) unless either Party provides notice of non-renewal to the other Party at least thirty (30) days prior to the end of the then-current Term.</p>
          <p className="mb-4"><strong>10.2. Termination.</strong></p>
          <ul className="mb-4 list-none pl-6 space-y-2">
            <li>(a) Notwithstanding anything to the contrary in the Agreement, Provider may terminate an Order Form, any SOW, or the Agreement generally without cause upon ten (10) days&rsquo; prior written notice to Customer.</li>
            <li>(b) In addition to any other express termination right set forth elsewhere in this Agreement either Party may terminate the Agreement, effective on written notice to the other Party, if (i) the other Party materially breaches the Agreement and such breach: (A) is incapable of cure; or (B) being capable of cure, remains uncured thirty (30) days after the non-breaching Party provides the breaching Party with written notice of such breach, or (ii) if the other Party: (A) becomes insolvent or is generally unable to pay, or fails to pay, its debts as they become due; (B) files or has filed against it, a petition for voluntary or involuntary bankruptcy or otherwise becomes subject, voluntarily or involuntarily, to any proceeding under any domestic or foreign bankruptcy or insolvency Law, in each case that is not discharged within sixty (60) days; (C) makes or seeks to make a general assignment for the benefit of its creditors; or (D) applies for or has appointed a receiver, trustee, custodian, or similar agent appointed by order of any court of competent jurisdiction to take charge of or sell any material portion of its property or business.</li>
          </ul>
          <p className="mb-4"><strong>10.3. Effect of Termination or Expiration.</strong> Upon any expiration or termination of the Agreement, except as expressly otherwise provided in the Agreement:</p>
          <ul className="mb-4 list-none pl-6 space-y-2">
            <li>(a) all rights, licenses, consents, and authorizations granted by either Party to the other hereunder will immediately terminate;</li>
            <li>(b) each Party shall immediately cease all use of any Confidential Information of the other Party and (i) promptly return or destroy, at the Receiving Party&rsquo;s election and subject to applicable Law, all documents and tangible materials containing, reflecting, incorporating, or based on Confidential Information; and (ii) permanently erase all Confidential Information from all systems the Receiving Party directly or indirectly controls, provided that, for clarity, Provider&rsquo;s obligations under this Section 10.3 do not apply to any Resultant Data or Usage Data; and</li>
            <li>(c) notwithstanding anything to the contrary in the Agreement, the Receiving Party may retain Confidential Information (i) to the extent and for so long as required by applicable Law and (ii) in the Receiving Party&rsquo;s backups, archives, and disaster recovery systems until such Confidential Information is deleted in the ordinary course. For the avoidance of doubt, all information and materials described in this Section 10.3(c) will remain subject to all confidentiality, security, and other applicable requirements of the Agreement.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-10 mb-4">11. User Contributions &amp; Media Release</h2>
          <p className="mb-4">Client agrees that any content provided to the Company — whether written, audio, video, or visual — including but not limited to comments, testimonials, submitted materials, Zoom recordings, and participation in any recorded sessions, may be captured, recorded, and used by the Company for marketing, promotional, educational, or commercial purposes. This includes but is not limited to use on social media, websites, advertisements, sales materials, and internal training. By engaging with the Company, the Client grants the Company a perpetual, irrevocable, worldwide, royalty-free license to use, reproduce, edit, distribute, and publicly display such content, in whole or in part, in any format or medium now known or later developed. If the Client does not wish for specific content to be used, they must notify the Company in writing in advance of the recording or submission. Any such opt-out will apply only to future content, not to content already created or used prior to notice.</p>

          <h2 className="text-2xl font-bold mt-10 mb-4">12. Miscellaneous</h2>
          <p className="mb-4"><strong>12.1. Force Majeure.</strong> Provider is excused from performance of the Agreement to the extent that performance is prevented, delayed or obstructed by causes beyond its reasonable control.</p>
          <p className="mb-4"><strong>12.2. Entire Agreement.</strong> This Agreement (including any modification hereof in accordance with Section 11.6), together with the Order Form, any SOW, and Provider&rsquo;s Privacy Policy, represents the sole and complete agreement between Customer and Provider concerning its subject matter, and supersedes all prior agreements (both written and oral) between the Parties with respect thereto.</p>
          <p className="mb-4"><strong>12.3. Severability.</strong> If any term or provision of the Agreement is held to be invalid, illegal or unenforceable for any reason, such provision will be reformed to the extent necessary to make it enforceable to the maximum extent permissible so as to effect the intent of the Parties, and the remainder of the Agreement will continue in full force and effect.</p>
          <p className="mb-4"><strong>12.4. Governing Law; Mediation; Arbitration.</strong></p>
          <ul className="mb-4 list-none pl-6 space-y-2">
            <li>(a) Utah law governs the Agreement without reference to its conflict of law principles.</li>
            <li>(b) The Parties shall first attempt to resolve any dispute arising out of or related to the Agreement (“Dispute”) shall first be submitted to the senior management of Provider and Customer for attempted resolution of the Dispute. Senior management shall discuss the problem and negotiate in good faith to resolve the Dispute without necessity of any formal proceeding relating thereto. If senior management, within fifteen (15) calendar days of their first communication have not resolved the Dispute, the Parties shall immediately thereafter submit the Dispute to mediation with a mediator mutually chosen by the Parties.</li>
            <li>(c) If the chosen mediator is unable to resolve the Dispute within a reasonable time, as determined by the mediator (and not to exceed thirty (30) calendar days after the Parties meet for mediation), the mediator will issue a written statement to the Parties to that effect and the complaining Party may then pursue binding arbitration and the Parties will immediately thereafter submit the Dispute to binding arbitration in accordance with the commercial rules of the American Arbitration Association then in effect (the submission date to be deemed the “Arbitration Date”).
              <ul className="mt-2 list-none pl-6 space-y-2">
                <li>(i) The Parties shall mutually choose a single commercial arbitrator with substantial experience in resolving complex commercial contract disputes. If the Parties cannot agree upon the arbitrator within fifteen (15) days of the Arbitration Date, then a single arbitrator will be selected in accordance with the rules of the American Arbitration Association.</li>
                <li>(ii) The arbitrator will have the authority to grant specific performance and to allocate between the Parties the costs of arbitration (including service fees, arbitrator fees and all other fees related to the arbitration) in such equitable manner as the arbitrator may determine.</li>
                <li>(iii) The non-prevailing Party in the arbitration shall pay the prevailing Party&rsquo;s reasonable costs and expenses incurred in connection therewith (including reasonable attorney fees and payment for the arbitrator).</li>
                <li>(iv) Judgment upon the award so rendered may be entered in a court having jurisdiction or application may be made to such court for judicial acceptance of any award and an order of enforcement, as the case may be.</li>
                <li>(v) Notwithstanding the foregoing, either Party may institute an action in a court of proper jurisdiction for preliminary injunctive relief pending a final decision by the arbitrator, provided that a permanent injunction and damages shall only be awarded by the arbitrator.</li>
              </ul>
            </li>
            <li>(d) The Parties must institute any permitted legal suit, action, or proceeding arising out of or related to the Agreement exclusively in the federal or state courts in and for Salt Lake County, Utah, and each Party irrevocably submits to the exclusive jurisdiction of such courts in any such suit, action, or proceeding. Service of process, summons, notice, or other document by mail to such Party&rsquo;s address set forth herein is effective service of process for any suit, action, or other proceeding brought in any such court. Each Party irrevocably and unconditionally waives any right it may have to a trial by jury in respect of any legal action arising out of or relating to the Agreement or the transactions contemplated hereby.</li>
          </ul>
          <p className="mb-4"><strong>12.5. Notices.</strong> Any notices to Provider or to Customer must be sent to Provider&rsquo;s or Customer&rsquo;s, as applicable, address, via personal delivery, registered or certified mail, overnight courier, or email (with confirmation of transmission) and are deemed given (a) if delivered personally, upon receipt; (b) if delivered by registered or certified mail, three business days following deposit with the USPS; (c) if delivered by overnight courier, on the business day following deposit with such courier; and (d) if delivered by email, when sent, if sent during the recipient&rsquo;s normal business hours, and otherwise on the next business day. Each Party&rsquo;s address for service of notices is included on the applicable Order Form.</p>
          <p className="mb-4"><strong>12.6. Changes to this Agreement.</strong> At certain times, Provider may in its discretion may make revisions to this Agreement. Provider will notify Customer of any such changes by posting notices through the Services or by emailing or otherwise notifying Customer, as appropriate in the circumstances. If Customer continues using the Services after the effective date of the changes, Customer is deemed to have accepted the revisions. If Customer does not agree to the revisions, Customer may terminate this Agreement by sending a termination email to info@enzy.ai.</p>
          <p className="mb-4"><strong>12.7. Waiver.</strong> No amendment to or modification of the Agreement is effective unless it is in writing, identified as an amendment to the Agreement and signed by each Party. No waiver by any Party of any of the provisions hereof is effective unless explicitly set forth in writing and signed by the Party so waiving. A waiver of any default is not a waiver of any subsequent default.</p>
          <p className="mb-4"><strong>12.8. Assignment and Change of Control.</strong> Customer may not assign, delegate, or otherwise transfer any of Customer&rsquo;s rights or obligations in the Agreement without Provider&rsquo;s prior written consent, and any such attempt is void. No permitted assignment, delegation, or transfer will relieve Customer of any of its obligations or performance under the Agreement. Provider may terminate the Agreement in the event of a merger, reorganization or other transaction resulting in a change of control of the Customer, effective immediately upon notice of such termination to the Customer or to the surviving entity to which the Customer undergoes such change of control. The Agreement is binding upon and inures to the benefit of any respective successors and permitted assigns of the Parties hereto.</p>
          <p className="mb-4"><strong>12.9. No Third-Party Beneficiaries.</strong> The Agreement is for the sole benefit of the Parties and their respective successors and permitted assigns and nothing herein, express or implied, is intended to or confer upon any other person any legal or equitable right, benefit, or remedy of any nature whatsoever under or by reason of the Agreement.</p>
          <p className="mb-4"><strong>12.10. Relationship of the Parties.</strong> The relationship between Provider and Customer is one of independent contractors and nothing contained in the Agreement may be construed as creating any agency, partnership, joint venture, or other form of joint enterprise, employment, or fiduciary relationship between the Parties, and neither Party has authority to contract for or bind the other Party in any manner whatsoever.</p>
          <p className="mb-4"><strong>12.11. Survival.</strong> Any provision that should by its nature survive the termination or expiration of the Agreement, does survive.</p>
          <p className="mb-4"><strong>12.12. Equitable Relief.</strong> Each Party acknowledges that a breach or threatened breach by such Party of any of its obligations could cause the other Party irreparable harm for which monetary damages would not be an adequate remedy and that, in the event of such breach or threatened breach, the other Party will be entitled to equitable relief, including a restraining order, an injunction, specific performance, and any other relief that may be available from any court, without any requirement to post a bond or other security, or to prove actual damages or that monetary damages are not an adequate remedy. Such remedies are not exclusive and are in addition to all other remedies that may be available at Law, in equity, or otherwise.</p>
          <p className="mb-4"><strong>12.13. Counterparts.</strong> The Parties may execute Order Forms and SOWs in counterparts, each of which is deemed an original, but all of which together are deemed to be one and the same agreement.</p>
          <p className="mb-4"><strong>12.14. Reservation of Rights.</strong> Provider reserves for itself any right not expressly set forth in the Agreement.</p>

          <h2 className="text-2xl font-bold mt-12 mb-2">Exhibit A — Service Level Addendum</h2>
          <p className="mb-4">The Parties incorporate this Service Level Addendum into the Agreement as if fully set forth therein.</p>

          <h3 className="text-xl font-bold mt-8 mb-2">I. Availability</h3>
          <p className="mb-4"><strong>A. Availability Requirement.</strong> Provider shall make the Services Available, as measured over the course of each calendar month during the Term and any additional periods during which Provider does or is required to provide any Services (each such calendar month, a “Service Period”), at least 99.5% of the time, excluding only the time the Services are not Available solely as a result of one or more Exceptions set forth in Section I(B) below (“Availability Requirement”). “Available” means the Services are available and operable for access and use by Customer and its Authorized Users over the Internet in full conformity with their intended specifications and use application. “Availability” has a correlative meaning. The Services are not considered Available in the event of any performance degradation that renders the Services substantially unavailable.</p>
          <p className="mb-4"><strong>B. Exceptions.</strong> No period of Service degradation or inoperability will be included in calculating Availability to the extent that such downtime or degradation is due to any of the following (“Exceptions”): (i) Customer&rsquo;s misuse of the Services; (ii) failures of Customer&rsquo;s or its Authorized Users&rsquo; Internet connectivity; (iii) Customer&rsquo;s or any of its Authorized Users&rsquo; failure to meet any minimum hardware or software requirements required to run the Services; (iv) any event of force majeure or other event or occurrence out of Provider&rsquo;s reasonable control; or (v) Scheduled Downtime.</p>
          <p className="mb-4"><strong>C. Scheduled Downtime.</strong> Provider shall notify Customer at least twenty-four (24) hours in advance of all scheduled outages of the Services in whole or in part (“Scheduled Downtime”). All such Scheduled Downtime will: (i) last no longer than two hours; (ii) be scheduled between the hours of 1:00 a.m. and 5:00 a.m., Mountain Time; and (iii) occur no more frequently than once per week; provided, that Provider may request for Customer&rsquo;s approval, extensions of Scheduled Downtime above and such approval by Customer may not be unreasonably withheld or delayed.</p>
          <p className="mb-4"><strong>D. Remedies for Service Availability Failures.</strong> If the actual Availability of the Services is less than the Availability Requirement for any Service Period, such failure constitutes a Service Error for which Provider shall issue to Customer the corresponding service credits as set forth in the chart below (“Service Availability Credits”):</p>
          <div className="overflow-x-auto mb-4">
            <table className="w-full text-left text-sm border-collapse">
              <thead>
                <tr className="border-b border-current/20">
                  <th className="py-2 pr-4 align-top font-semibold">Required Availability Service Level</th>
                  <th className="py-2 pr-4 align-top font-semibold">Calculation Formula</th>
                  <th className="py-2 align-top font-semibold">Service Availability Credits</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">Services shall be Available 99.5% of the time during each Service Period excluding periods Hosted Services are not Available due to an Exception.</td>
                  <td className="py-2 pr-4">(Total Minutes in the Service Period that the Services are Available – Total Minutes in Service Period Services are not Available Due to an Exception) ÷ (Scheduled Uptime − Total Minutes in Service Period Services are not Available Due to an Exception) × 100 = Percentage Uptime. No Service Availability Credits will be given for any Service Period in which Percentage Uptime equals or exceeds the Availability Requirement.</td>
                  <td className="py-2">Customer is entitled to a Service Availability Credit of five percent (5%) of the Fees payable for Services provided during the Service Period for each one percent (1%) by which Percentage Uptime is less than the Availability Requirement, such credit not to exceed 100%.</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="mb-4"><strong>E. Payment of Service Availability Credits.</strong> The Parties acknowledge that each of the Service Availability Credits assessed pursuant to the above will, at Provider&rsquo;s option, be credited or set off against any Fees or other charges payable to Provider under the Agreement or be payable to Customer upon demand. No Service Availability Credits for any Service Period can exceed the total amount of Fees that would be payable for that Service Period if the Services were fully provided in accordance with this Agreement.</p>
          <p className="mb-4"><strong>F. Additional Remedies.</strong> If the actual Availability of the Services is less than the Availability Requirement in any two of four consecutive Service Periods, then, in addition to all other remedies available to Customer, Customer may terminate this Agreement on written notice to Provider with no liability, obligation, or penalty to Customer by reason of such termination.</p>

          <h3 className="text-xl font-bold mt-8 mb-2">II. Support and Maintenance</h3>
          <p className="mb-4"><strong>A. Support and Maintenance Services.</strong> Provider shall provide account management services to Customer, which must include the following maintenance and support services (collectively, “Support Services”) to Customer in connection with its access to and use of the Services (all of which are included in the Services, and Provider will not assess any additional Fees, costs or charges for such Support Services):</p>
          <ul className="mb-4 list-none pl-6 space-y-2">
            <li>i. Provider shall: (a) correct any and all failures of the Service to be Available or otherwise perform in accordance with the Agreement (each, a “Service Error”) in accordance with the Support Service Level Requirements set forth below, including by providing defect repair, programming corrections and remedial programming; (b) provide online access to technical support bulletins and other user support information and forums, to the full extent Provider makes such resources available to its other customers; and (c) respond to and Resolve Support Requests (as such terms are defined below) as specified herein.</li>
            <li>ii. Provider shall continuously monitor and manage the Services to optimize Availability that meets or exceeds the Availability Requirement. Such monitoring and management will include: (a) proactively monitoring on a 24 hour by seven day basis all Service functions, servers, firewall, and other components of Service security; (b) if such monitoring identifies, or Provider otherwise becomes aware of, any circumstance that is reasonably likely to threaten the Availability of the Service, taking all necessary and reasonable remedial measures to promptly eliminate such threat and ensure full Availability; and (c) if Provider receives knowledge that the Service or any Service function or component is not Available (including by written notice from Customer pursuant to the procedures set forth herein): (1) confirming (or disconfirming) the outage by a direct check of the associated facility or facilities; (2) if Provider&rsquo;s facility check in accordance with clause (1) above confirms a Service outage in whole or in part: (A) notifying Customer in writing pursuant to the procedures set forth herein that an outage has occurred, providing such details as may be available, including a Provider trouble ticket number, if appropriate, and time of outage; and (B) working all problems causing and caused by the outage until they are Resolved as Critical Service Errors in accordance with the Support Request Classification set forth below; and (3) notifying Customer that Provider has fully corrected the outage and any related problems, along with any pertinent findings or action taken to close the trouble ticket.</li>
            <li>iii. Provider shall continuously maintain the Services to optimize Availability that meets or exceeds the Availability Requirement. Such maintenance services will include providing to Customer and its Authorized Users: (a) all updates, bug fixes, enhancements, new releases, new versions, and other improvements to the Services, including, without limitation, the Service software, that Provider provides at no additional charge to its other similarly situated customers; and (b) all such services and repairs as are required to maintain the Services or are ancillary, necessary, or otherwise related to Customer&rsquo;s or its Authorized Users&rsquo; access to or use of the Services, so that the Services operate properly in accordance with this Agreement.</li>
          </ul>
          <p className="mb-4"><strong>B. Support Service Level Requirements.</strong> Provider shall correct all Service Errors and respond to and Resolve all Support Requests in accordance with the required times and other terms and conditions set forth below (“Support Service Level Requirements”) and this Agreement, as follows:</p>
          <p className="mb-4">i. Customer shall classify its requests for Service Error corrections in accordance with the descriptions set forth in the chart below (each a “Support Request”). The customer service manager shall notify Provider of Support Requests by email, telephone, or such other means as the Parties may hereafter agree to in writing.</p>
          <div className="overflow-x-auto mb-4">
            <table className="w-full text-left text-sm border-collapse">
              <thead>
                <tr className="border-b border-current/20">
                  <th className="py-2 pr-4 align-top font-semibold">Support Request Classification</th>
                  <th className="py-2 align-top font-semibold">Description</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">Critical Service Error</td>
                  <td className="py-2">Issue affecting entire system or single critical production function; system down or operating in materially degraded state; data integrity at risk; material financial impact; declared a Critical Support Request by the Customer; or widespread access interruptions.</td>
                </tr>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">High Service Error</td>
                  <td className="py-2">Primary component failure that materially impairs its performance; or data entry or access is materially impaired on a limited basis.</td>
                </tr>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">Medium Service Error</td>
                  <td className="py-2">Service is operating with minor issues that can be addressed with a work around.</td>
                </tr>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">Low Service Error</td>
                  <td className="py-2">Request for assistance, information, or services that are routine in nature.</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="mb-4">ii. Response and Resolution times will be measured from the time Provider receives a Support Request until the respective times Provider has (a) responded to, in the case of response time, and (b) Resolved such Support Request, in the case of Resolution time. “Resolve” (including “Resolved”, “Resolution” and correlative capitalized terms) means that, as to any Service Error, Provider has provided Customer the corresponding Service Error correction and Customer has confirmed such correction and its acceptance thereof. Provider shall respond to and Resolve all Service Errors within the following times based on the severity of the Service Error:</p>
          <div className="overflow-x-auto mb-4">
            <table className="w-full text-left text-sm border-collapse">
              <thead>
                <tr className="border-b border-current/20">
                  <th className="py-2 pr-4 align-top font-semibold">Classification</th>
                  <th className="py-2 pr-4 align-top font-semibold">Required Response Time</th>
                  <th className="py-2 pr-4 align-top font-semibold">Required Resolution Time</th>
                  <th className="py-2 pr-4 align-top font-semibold">Credits (Response)</th>
                  <th className="py-2 align-top font-semibold">Credits (Resolution)</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">Critical Service Error</td>
                  <td className="py-2 pr-4">Within 15 minutes</td>
                  <td className="py-2 pr-4">Within 1 hour</td>
                  <td className="py-2 pr-4">5% of monthly Fees</td>
                  <td className="py-2">5% of monthly Fees</td>
                </tr>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">High Service Error</td>
                  <td className="py-2 pr-4">Within 45 minutes</td>
                  <td className="py-2 pr-4">Within 3 hours</td>
                  <td className="py-2 pr-4">5% of monthly Fees</td>
                  <td className="py-2">5% of monthly Fees</td>
                </tr>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">Medium Service Error</td>
                  <td className="py-2 pr-4">Within 1 hour</td>
                  <td className="py-2 pr-4">Within 48 hours</td>
                  <td className="py-2 pr-4">2% of monthly Fees</td>
                  <td className="py-2">5% of monthly Fees</td>
                </tr>
                <tr className="border-b border-current/10 align-top">
                  <td className="py-2 pr-4">Low Service Error</td>
                  <td className="py-2 pr-4">Within 4 hours</td>
                  <td className="py-2 pr-4">As soon as reasonably practicable, but no later than 3 days</td>
                  <td className="py-2 pr-4">2% of monthly Fees</td>
                  <td className="py-2">5% of monthly Fees</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="mb-4">iii. <strong>Support Service Level Credits.</strong> Provider acknowledges that its failure to achieve any of the Support Service Level Requirements above constitutes a Service Level Failure for which Provider shall issue to Customer the corresponding service credits set forth in the chart above (“Support Service Level Credits”). The Parties acknowledge that each of the Support Service Level Credits assessed pursuant to the above will, at Provider&rsquo;s option, be credited or set off against any Fees or other charges payable to Provider under this Agreement or be payable to Customer upon demand. No Support Service Level Credits for any Service Period will exceed the total amount of Fees that would be payable for that Service Period if the Services were fully provided in accordance with this Agreement.</p>
          <p className="mb-4"><strong>III. Cumulative Remedies.</strong> For the avoidance of doubt, Provider acknowledges that the remedies provided in this Schedule are in addition to and cumulative to any other rights and remedies available to Customer under the Agreement or in law or at equity.</p>

          <div className="mt-16 pt-8 border-t border-current/10">
            <p className="text-sm opacity-70">For questions about these Terms and Conditions, please contact us at info@enzy.ai</p>
          </div>
        </div>
      </main>
  );
}
